### ISSUE TITLE
LW 21

### ISSUE THREAD

**Issue by UsingCoding** [EldarMuhamethanov/OP#6]
### 21.1

- [x] У вас определенно есть неиспользуемые переменные
### 21.2

- [x] +прошлое замечание

- [x] Эта проверка избыточна, т.к. при импорте вы уже проверяете входит ли символ в алфавит
https://github.com/EldarMuhamethanov/OP/blob/e9d5f7929a17d858637046a591a3712b3f0bc9a8/lw21/2.pas#L58

### 21.3

- [x] Раз у вас программа программа теперь дешифрует, то стоит процедуру, выполняющую основную логику, назвать соответствующее

**Comment by EldarMuhamethanov** [comment]
> * [ ]  Эта проверка избыточна, т.к. при импорте вы уже проверяете входит ли символ в алфавит
>   https://github.com/EldarMuhamethanov/OP/blob/e9d5f7929a17d858637046a591a3712b3f0bc9a8/lw21/2.pas#L58

Тут второе условие сделано для ситуации, если в исходном шифре не будет шифровки для символа который входит в массив. Если эту ситуацию не рассматривать, то тогда будет проблема в случае если не задать шифр для буквы E, например, и затем написать ее, то на ее месте будет пробел. Для этого я и создаю CodeBunch который хранит все зашифрованные символы

**Comment by EldarMuhamethanov** [comment]
Остальное я исправил

**Comment by UsingCoding** [comment]
> > * [ ]   Эта проверка избыточна, т.к. при импорте вы уже проверяете входит ли символ в алфавит
> >   https://github.com/EldarMuhamethanov/OP/blob/e9d5f7929a17d858637046a591a3712b3f0bc9a8/lw21/2.pas#L58
> 
> Тут второе условие сделано для ситуации, если в исходном шифре не будет шифровки для символа который входит в массив. Если эту ситуацию не рассматривать, то тогда будет проблема в случае если не задать шифр для буквы E, например, и затем написать ее, то на ее месте будет пробел. Для этого я и создаю CodeBunch который хранит все зашифрованные символы

Не совсем, у вас в этом условии две проверки, проверка на вхождении в алфавит нивелируется проверкой на вхождение в CodeBunch, т.к. если символ в CodeBunch, то он и в алфавите. Так же если в шифре написать `E-`, где после `-` начинается новая строка, то ваша программа выведет ошибку формата

**Comment by EldarMuhamethanov** [comment]
> > > * [ ]    Эта проверка избыточна, т.к. при импорте вы уже проверяете входит ли символ в алфавит
> > >   https://github.com/EldarMuhamethanov/OP/blob/e9d5f7929a17d858637046a591a3712b3f0bc9a8/lw21/2.pas#L58
> > 
> > 
> > Тут второе условие сделано для ситуации, если в исходном шифре не будет шифровки для символа который входит в массив. Если эту ситуацию не рассматривать, то тогда будет проблема в случае если не задать шифр для буквы E, например, и затем написать ее, то на ее месте будет пробел. Для этого я и создаю CodeBunch который хранит все зашифрованные символы
> 
> Не совсем, у вас в этом условии две проверки, проверка на вхождении в алфавит нивелируется проверкой на вхождение в CodeBunch, т.к. если символ в CodeBunch, то он и в алфавите. Так же если в шифре написать `E-`, где после `-` начинается новая строка, то ваша программа выведет ошибку формата

Чтож действительно так, Теперь понял, исправил
